// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/opskat/opskat/internal/service/oss_svc (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=./mock_ossclient/mock.go -package=mock_ossclient github.com/opskat/opskat/internal/service/oss_svc Client
//

// Package mock_ossclient is a generated GoMock package.
package mock_ossclient

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	oss_svc "github.com/opskat/opskat/internal/service/oss_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BucketExists mocks base method.
func (m *MockClient) BucketExists(ctx context.Context, bucket string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", ctx, bucket)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockClientMockRecorder) BucketExists(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockClient)(nil).BucketExists), ctx, bucket)
}

// CopyObject mocks base method.
func (m *MockClient) CopyObject(ctx context.Context, srcBucket, srcKey, dstBucket, dstKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", ctx, srcBucket, srcKey, dstBucket, dstKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockClientMockRecorder) CopyObject(ctx, srcBucket, srcKey, dstBucket, dstKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockClient)(nil).CopyObject), ctx, srcBucket, srcKey, dstBucket, dstKey)
}

// GetObject mocks base method.
func (m *MockClient) GetObject(ctx context.Context, bucket, key string) (io.ReadCloser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucket, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientMockRecorder) GetObject(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockClient)(nil).GetObject), ctx, bucket, key)
}

// ListBuckets mocks base method.
func (m *MockClient) ListBuckets(ctx context.Context) ([]oss_svc.BucketItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuckets", ctx)
	ret0, _ := ret[0].([]oss_svc.BucketItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuckets indicates an expected call of ListBuckets.
func (mr *MockClientMockRecorder) ListBuckets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuckets", reflect.TypeOf((*MockClient)(nil).ListBuckets), ctx)
}

// ListObjects mocks base method.
func (m *MockClient) ListObjects(ctx context.Context, bucket, prefix string, maxKeys int, startAfter string) ([]oss_svc.ObjectItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucket, prefix, maxKeys, startAfter)
	ret0, _ := ret[0].([]oss_svc.ObjectItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockClientMockRecorder) ListObjects(ctx, bucket, prefix, maxKeys, startAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockClient)(nil).ListObjects), ctx, bucket, prefix, maxKeys, startAfter)
}

// PresignGet mocks base method.
func (m *MockClient) PresignGet(ctx context.Context, bucket, key string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignGet", ctx, bucket, key, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGet indicates an expected call of PresignGet.
func (mr *MockClientMockRecorder) PresignGet(ctx, bucket, key, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGet", reflect.TypeOf((*MockClient)(nil).PresignGet), ctx, bucket, key, expiry)
}

// PresignPut mocks base method.
func (m *MockClient) PresignPut(ctx context.Context, bucket, key string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignPut", ctx, bucket, key, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPut indicates an expected call of PresignPut.
func (mr *MockClientMockRecorder) PresignPut(ctx, bucket, key, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPut", reflect.TypeOf((*MockClient)(nil).PresignPut), ctx, bucket, key, expiry)
}

// PutObject mocks base method.
func (m *MockClient) PutObject(ctx context.Context, bucket, key string, r io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucket, key, r, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockClientMockRecorder) PutObject(ctx, bucket, key, r, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockClient)(nil).PutObject), ctx, bucket, key, r, size, contentType)
}

// RemoveObject mocks base method.
func (m *MockClient) RemoveObject(ctx context.Context, bucket, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", ctx, bucket, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockClientMockRecorder) RemoveObject(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockClient)(nil).RemoveObject), ctx, bucket, key)
}

// RemoveObjects mocks base method.
func (m *MockClient) RemoveObjects(ctx context.Context, bucket string, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObjects", ctx, bucket, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObjects indicates an expected call of RemoveObjects.
func (mr *MockClientMockRecorder) RemoveObjects(ctx, bucket, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObjects", reflect.TypeOf((*MockClient)(nil).RemoveObjects), ctx, bucket, keys)
}

// StatObject mocks base method.
func (m *MockClient) StatObject(ctx context.Context, bucket, key string) (oss_svc.ObjectItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatObject", ctx, bucket, key)
	ret0, _ := ret[0].(oss_svc.ObjectItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatObject indicates an expected call of StatObject.
func (mr *MockClientMockRecorder) StatObject(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatObject", reflect.TypeOf((*MockClient)(nil).StatObject), ctx, bucket, key)
}
