// Code generated by MockGen. DO NOT EDIT.
// Source: ../forward.go
//
// Generated by this command:
//
//	mockgen -source=../forward.go -destination=forward.go -package=mock_forward_repo
//

// Package mock_forward_repo is a generated GoMock package.
package mock_forward_repo

import (
	context "context"
	reflect "reflect"

	forward_entity "github.com/opskat/opskat/internal/model/entity/forward_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockForwardRepo is a mock of ForwardRepo interface.
type MockForwardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockForwardRepoMockRecorder
	isgomock struct{}
}

// MockForwardRepoMockRecorder is the mock recorder for MockForwardRepo.
type MockForwardRepoMockRecorder struct {
	mock *MockForwardRepo
}

// NewMockForwardRepo creates a new mock instance.
func NewMockForwardRepo(ctrl *gomock.Controller) *MockForwardRepo {
	mock := &MockForwardRepo{ctrl: ctrl}
	mock.recorder = &MockForwardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForwardRepo) EXPECT() *MockForwardRepoMockRecorder {
	return m.recorder
}

// CreateConfig mocks base method.
func (m *MockForwardRepo) CreateConfig(ctx context.Context, config *forward_entity.ForwardConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfig indicates an expected call of CreateConfig.
func (mr *MockForwardRepoMockRecorder) CreateConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfig", reflect.TypeOf((*MockForwardRepo)(nil).CreateConfig), ctx, config)
}

// DeleteConfig mocks base method.
func (m *MockForwardRepo) DeleteConfig(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfig", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockForwardRepoMockRecorder) DeleteConfig(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfig", reflect.TypeOf((*MockForwardRepo)(nil).DeleteConfig), ctx, id)
}

// DeleteRulesByConfigID mocks base method.
func (m *MockForwardRepo) DeleteRulesByConfigID(ctx context.Context, configID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRulesByConfigID", ctx, configID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRulesByConfigID indicates an expected call of DeleteRulesByConfigID.
func (mr *MockForwardRepoMockRecorder) DeleteRulesByConfigID(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRulesByConfigID", reflect.TypeOf((*MockForwardRepo)(nil).DeleteRulesByConfigID), ctx, configID)
}

// FindConfig mocks base method.
func (m *MockForwardRepo) FindConfig(ctx context.Context, id int64) (*forward_entity.ForwardConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindConfig", ctx, id)
	ret0, _ := ret[0].(*forward_entity.ForwardConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindConfig indicates an expected call of FindConfig.
func (mr *MockForwardRepoMockRecorder) FindConfig(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindConfig", reflect.TypeOf((*MockForwardRepo)(nil).FindConfig), ctx, id)
}

// ListConfigs mocks base method.
func (m *MockForwardRepo) ListConfigs(ctx context.Context) ([]*forward_entity.ForwardConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigs", ctx)
	ret0, _ := ret[0].([]*forward_entity.ForwardConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigs indicates an expected call of ListConfigs.
func (mr *MockForwardRepoMockRecorder) ListConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigs", reflect.TypeOf((*MockForwardRepo)(nil).ListConfigs), ctx)
}

// ListRulesByConfigID mocks base method.
func (m *MockForwardRepo) ListRulesByConfigID(ctx context.Context, configID int64) ([]*forward_entity.ForwardRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRulesByConfigID", ctx, configID)
	ret0, _ := ret[0].([]*forward_entity.ForwardRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRulesByConfigID indicates an expected call of ListRulesByConfigID.
func (mr *MockForwardRepoMockRecorder) ListRulesByConfigID(ctx, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRulesByConfigID", reflect.TypeOf((*MockForwardRepo)(nil).ListRulesByConfigID), ctx, configID)
}

// ReplaceRules mocks base method.
func (m *MockForwardRepo) ReplaceRules(ctx context.Context, configID int64, rules []*forward_entity.ForwardRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRules", ctx, configID, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceRules indicates an expected call of ReplaceRules.
func (mr *MockForwardRepoMockRecorder) ReplaceRules(ctx, configID, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRules", reflect.TypeOf((*MockForwardRepo)(nil).ReplaceRules), ctx, configID, rules)
}

// UpdateConfig mocks base method.
func (m *MockForwardRepo) UpdateConfig(ctx context.Context, config *forward_entity.ForwardConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockForwardRepoMockRecorder) UpdateConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockForwardRepo)(nil).UpdateConfig), ctx, config)
}
