// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/ai_provider_repo/ai_provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/ai_provider_repo/ai_provider.go -destination=internal/repository/ai_provider_repo/mock_ai_provider_repo/ai_provider.go -package=mock_ai_provider_repo
//

// Package mock_ai_provider_repo is a generated GoMock package.
package mock_ai_provider_repo

import (
	context "context"
	reflect "reflect"

	ai_provider_entity "github.com/opskat/opskat/internal/model/entity/ai_provider_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAIProviderRepo is a mock of AIProviderRepo interface.
type MockAIProviderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAIProviderRepoMockRecorder
	isgomock struct{}
}

// MockAIProviderRepoMockRecorder is the mock recorder for MockAIProviderRepo.
type MockAIProviderRepoMockRecorder struct {
	mock *MockAIProviderRepo
}

// NewMockAIProviderRepo creates a new mock instance.
func NewMockAIProviderRepo(ctrl *gomock.Controller) *MockAIProviderRepo {
	mock := &MockAIProviderRepo{ctrl: ctrl}
	mock.recorder = &MockAIProviderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIProviderRepo) EXPECT() *MockAIProviderRepoMockRecorder {
	return m.recorder
}

// ClearActive mocks base method.
func (m *MockAIProviderRepo) ClearActive(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearActive", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearActive indicates an expected call of ClearActive.
func (mr *MockAIProviderRepoMockRecorder) ClearActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearActive", reflect.TypeOf((*MockAIProviderRepo)(nil).ClearActive), ctx)
}

// Create mocks base method.
func (m *MockAIProviderRepo) Create(ctx context.Context, p *ai_provider_entity.AIProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAIProviderRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAIProviderRepo)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockAIProviderRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAIProviderRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAIProviderRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAIProviderRepo) Find(ctx context.Context, id int64) (*ai_provider_entity.AIProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*ai_provider_entity.AIProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAIProviderRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAIProviderRepo)(nil).Find), ctx, id)
}

// GetActive mocks base method.
func (m *MockAIProviderRepo) GetActive(ctx context.Context) (*ai_provider_entity.AIProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx)
	ret0, _ := ret[0].(*ai_provider_entity.AIProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockAIProviderRepoMockRecorder) GetActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockAIProviderRepo)(nil).GetActive), ctx)
}

// List mocks base method.
func (m *MockAIProviderRepo) List(ctx context.Context) ([]*ai_provider_entity.AIProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*ai_provider_entity.AIProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAIProviderRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAIProviderRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockAIProviderRepo) Update(ctx context.Context, p *ai_provider_entity.AIProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAIProviderRepoMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAIProviderRepo)(nil).Update), ctx, p)
}
